services:
  app:
#    build: .
    image: hatruong0701/web1:lasted
    container_name: java-web
    ports:
      - "80:8080"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dataweb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Passnhutren1

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=dataweb
      - MYSQL_ROOT_PASSWORD=Passnhutren1
    ports:
      - "3307:3306"  # ánh xạ 3307 trên máy sang 3306 trong container
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Dump2025:/docker-entrypoint-initdb.d
volumes:
  redis-data:
  mysql-data: